apiVersion: v1
kind: Secret
metadata:
  name: honk-twitter-config
type: Opaque
stringData:
  config-honk.json: |-
    {
      "TwitterConsumerKey": "",
      "TwitterConsumerSecretKey" : "",
      "TwitterAccessToken": "",
      "TwitterAccessSecret": "",
      "UnsplashClientID": "",
      "TwitterSearchCounts": "600"
    }
